<?php

/**
 * @file
 * mrb_ezfacility.module
 */


/**
 * Implements hook_theme().
 */
function mrb_ezfacility_theme() {
    return array(
        'mrb_operation_result' => array(
            'variables' => array(
                'data' => null,
            ),
            'template'  => 'templates/mrb-operation-result',
        ),
        'screen_page_block_theme' => array(
            'variables' => array(
                'data' => null,
            ),
            'template'  => 'templates/screen-page-block-theme',
        ),
    );
}

/**
 * Implements hook_menu().
 */
function mrb_ezfacility_menu()
{

    $items = array();

    $items['start-mrb-pulling'] = array(
        'title' => t('Meeting Room Booking'),
        'type' => MENU_CALLBACK,
        'page callback' => 'start_meeting_room_booking_pulling',
        'file' => 'mrb_admin.inc',
        'access arguments' => array('access content'),
    );

    return $items;
}

/**
 * Implements hook_block_info().
 */
function mrb_ezfacility_block_info() {

    $blocks['screen_page_block'] = array(
        'info' => t('Screen page block'),
        'cache' => DRUPAL_NO_CACHE
    );

    return $blocks;
}

/**
 * Implements hook_block_view().
 */
function tonic_sfaq_block_view($delta = '') {

    $block = array();
    switch ($delta) {
        case 'screen_page_block':
            $block['content'] = _callback_for_screen_page_block();
            break;
    }
    return $block;
}

function _callback_for_screen_page_block() {


    return theme( 'screen_page_block_theme', array('data' => []));
}
