<?php

/**
 * @file
 * mrb_ezfacility.module
 */

module_load_include('inc', 'mrb_ezfacility', 'mrb_admin');

/**
 * Implements hook_theme().
 */
function mrb_ezfacility_theme() {
    return array(
        'mrb_operation_result' => array(
            'variables' => array(
                'data' => null,
            ),
            'template'  => 'templates/mrb-operation-result',
        ),
        'screen_page_block_theme' => array(
            'variables' => array(
                'data' => null,
            ),
            'template'  => 'templates/screen-page-block-theme',
        ),
    );
}

/**
 * Implements hook_menu().
 */
function mrb_ezfacility_menu()
{

    $items = array();

    $items['start-mrb-pulling'] = array(
        'title' => t('Meeting Room Booking'),
        'type' => MENU_CALLBACK,
        'page callback' => 'start_meeting_room_booking_pulling',
        'file' => 'mrb_admin.inc',
        'access arguments' => array('access content'),
    );

    return $items;
}

/**
 * Implements hook_block_info().
 */
function mrb_ezfacility_block_info() {

    $blocks['screen_page_block'] = array(
        'info' => t('Screen page block'),
        'cache' => DRUPAL_NO_CACHE
    );

    return $blocks;
}

/**
 * Implements hook_block_view().
 */
function mrb_ezfacility_block_view($delta = '') {

    $block = array();
    switch ($delta) {
        case 'screen_page_block':
            $block['content'] = _callback_for_screen_page_block();
            break;
    }
    return $block;
}

/**
 * @return string
 * @throws Exception
 */
function _callback_for_screen_page_block() {


    $node = menu_get_object();
    $events = _get_all_events($node->field_facility['und'][0]['entity']->field_ez_facility_resources['und'][0]['target_id']);
    $data = array(
        'events' => $events,
    );

    return theme( 'screen_page_block_theme', array('data' => $data));
}

/**
 * @param $screen_facility_id
 * @return array
 */
function _get_all_events($screen_facility_id) {

    $query = db_select('field_data_field_location', 'fl');
    $query->fields('fl', array('entity_id', 'field_location_target_id'))
        ->condition('fl.field_location_target_id', $screen_facility_id);
    $results = $query->execute();

    $events = array();

    foreach($results as $result) {

        $event = node_load($result->entity_id);

        $today = new DateTime(date('Y-m-d H:i:s'));
        $end_date = new DateTime($event->field_schedule_date['und'][0]['value2']);

        if ($end_date >= $today) {
            $events[] = array(
                'nid' => $event->nid,
                'title' => $event->title,
                'date' => array(
                    'start_date' => date('Y-m-d', strtotime($event->field_schedule_date['und'][0]['value'])), // Y-m-d H:i A
                    'end_date' => date('Y-m-d', strtotime($event->field_schedule_date['und'][0]['value2'])),
                ),
            );
        }
    }

    return $events;
}

/**
 * @throws Exception
 */
function start_meeting_room_booking_pulling_from_rules() {

    $start_date = date('m/d/Y');
    $end_date = date('m/d/Y', time() + 86400);

    $mrb_data = call_ez_facility_for_mrb($start_date, $end_date);

    $previous_mrb = _get_previous_mrb($start_date, $end_date);

    foreach ($mrb_data as $mrb) {
        if (array_key_exists($mrb['ResourceID'], $previous_mrb)) {
            // Update existing mrb
            _update_existing_mrb($previous_mrb[$mrb['ResourceID']], $mrb);

        } else {
            // Create new mrb
            _create_new_mrb($mrb);
        }
    }
}
